/*
 * File: MyApp/store/Persons.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Persons', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Person'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'MyApp.model.Person',
            storeId: 'Persons',
            data: [
                {
                    Name: 'Leroy Mitchell',
                    Age: 31
                },
                {
                    Name: 'Evelyn Hill',
                    Age: 58
                },
                {
                    Name: 'Claude Nelson',
                    Age: 66
                },
                {
                    Name: 'Lydia Hernandez',
                    Age: 13
                },
                {
                    Name: 'Mae Ward',
                    Age: 94
                }
            ]
        }, cfg)]);
    }
});