/*
 * File: MyApp/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.View',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    id: 'MainView',
    itemId: 'mainView',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    margins: '0 5 0 0',
                    region: 'west',
                    itemId: 'grid',
                    title: 'Attending',
                    store: 'Persons',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            dataIndex: 'Name',
                            text: 'Name'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'Age',
                            text: 'Age',
                            format: '0'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    flex: 1,
                    region: 'center',
                    itemId: 'form',
                    bodyPadding: 10,
                    title: 'Edit Details',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Name',
                            name: 'name'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            fieldLabel: 'Age',
                            name: 'age',
                            decimalPrecision: 0
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            itemId: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'addButton',
                                    text: 'Add'
                                },
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    itemId: 'saveButton',
                                    text: 'Save'
                                },
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    itemId: 'deleteButton',
                                    text: 'Delete'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});